### ISSUE TITLE
pip distribution ?

### ISSUE THREAD

**Issue by Seraf** [kstaniek/fiblary#1]
Hello,

Thanks a lot for this lib.
Any chance to make it available on pypi please ?
https://pypi.python.org

I plan to use it for my project L.I.S.A (http://www.lisa-project.net) as I want to code a plugin for my HC2.

Thanks !

**Comment by kstaniek** [comment]
Hi Seraf,
thanks for your comment. I don't think this module is in the state to be published on pypi.
Still a lot of bugs to be fixed.
I'm just working on the issue when device has a room id = 0.
Cheers,
Klaudiusz

**Comment by Seraf** [comment]
Hi,

Ok, I have a lot of work to do on my side, but if needed don't hesitate to open an issue and I will try to work on these on my side as I have a HC2 too :)

Cheers

**Comment by kstaniek** [comment]
Thanks mate for the interest. You're always welcome with any comments and suggestions. I'm waiting for Fibaro to get more information about the new API. So far the library is prepared for handling new version. There are also some small issues. I work on it in best effort manner so don't have too much time.

**Comment by kstaniek** [comment]
Hi Julien,
I have made a lot of changes to the code and eventually removed the warlock
mode and json schema support. It was extremely slow and hard to maintain
due to continuous and big mess in the Fibaro API.

Now it is available as a package on PyPi.

pip install fiblaro

Cheers,
Klaudiusz

**Comment by Seraf** [comment]
Hi,

Thanks a lot for the update, it's a beautiful API !
